const filmActionTypes = {
	GET_FILMS_REQUEST: "GET_FILMS_REQUEST",
	GET_FILMS_SUCCESS: "GET_FILMS_SUCCESS",
	GET_FILMS_FAILURE: "GET_FILMS_FAILURE",
	SCOPED_GET_FILMS_REQUEST: "SCOPED_GET_FILMS_REQUEST",
	SCOPED_GET_FILMS_SUCCESS: "SCOPED_GET_FILMS_SUCCESS",
	SCOPED_GET_FILMS_FAILURE: "SCOPED_GET_FILMS_FAILURE",
}

export default filmActionTypes
