const peopleActionTypes = {
	GET_PEOPLE_REQUEST: "GET_PEOPLE_REQUEST",
	GET_PEOPLE_SUCCESS: "GET_PEOPLE_SUCCESS",
	GET_PEOPLE_FAILURE: "GET_PEOPLE_FAILURE",
	SCOPED_GET_PEOPLE_REQUEST: "SCOPED_GET_PEOPLE_REQUEST",
	SCOPED_GET_PEOPLE_SUCCESS: "SCOPED_GET_PEOPLE_SUCCESS",
	SCOPED_GET_PEOPLE_FAILURE: "SCOPED_GET_PEOPLE_FAILURE",
}

export default peopleActionTypes
