const planetActionTypes = {
	GET_PLANETS_REQUEST: "GET_PLANETS_REQUEST",
	GET_PLANETS_SUCCESS: "GET_PLANETS_SUCCESS",
	GET_PLANETS_FAILURE: "GET_PLANETS_REQUEST",
	SORT_PLANETS: "SORT_PLANETS",
}

export default planetActionTypes
